In [1]:
#import packages 

from glob import glob
import pandas as pd
import os
import shutil
import math
import numpy as np

folder_path="./dataset/subset/"
folders = glob(folder_path+'complete/*')

train_split=0.7
no_of_images=0

In [2]:
#split data to training and testing

def createFolder(path):
	if os.path.exists(path):
		shutil.rmtree(path)
	os.makedirs(path)

createFolder(folder_path+"train")
createFolder(folder_path+"test")

for folder in folders:
    images = glob(folder+'/*.jpg')
    name = folder.split('/')[-1]
    createFolder(folder_path+"train/"+name)
    createFolder(folder_path+"test/"+name)
    train_images=math.floor(train_split*len(images))
    for i,image in enumerate(images):
        if(i<=train_images-1):
            shutil.copy(image,folder_path+"train/"+name)
        else:
            shutil.copy(image,folder_path+"test/"+name)
        no_of_images+=1
    print(name)


In [3]:
# Importing the Keras libraries and packages
from keras.models import Sequential,save_model,load_model
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers.core import Dense, Dropout
from keras.applications import VGG16,Xception,ResNet50,nasnet
from keras.callbacks import ModelCheckpoint,EarlyStopping, TensorBoard

# Initialising the CNN
classifier = Sequential()
# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))
classifier.add(Dropout(0.2))
# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
classifier.add(Dropout(0.2))
# Step 3 - Flattening
classifier.add(Flatten())
# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 5, activation = 'softmax'))
# Compiling the CNN
classifier.compile(optimizer = 'adam',
                   loss = 'categorical_crossentropy', 
                   metrics = ['accuracy'])
classifier.summary()


Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
__________

In [ ]:

# Part 2 - Fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   horizontal_flip=True,
                                   rotation_range = 0.2,
                                   zoom_range = 0.2,
                                   width_shift_range = 0.2,
                                   height_shift_range = 0.2,)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory(folder_path+"train/",
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory(folder_path+"test/",
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

tensorboard=[TensorBoard(log_dir='logs/', histogram_freq=0, batch_size=32, write_graph=True, 
                      write_grads=False, write_images=False, embeddings_freq=0, embeddings_layer_names=None, 
                      embeddings_metadata=None)]

checkpointer = ModelCheckpoint(filepath='output_models', verbose=1, save_best_only=True)

classifier.fit_generator(training_set,steps_per_epoch = 12500/25,
                         epochs = 30,
                         validation_data = test_set,
                         validation_steps = 30,
                         callbacks =tensorboard)

Found 0 images belonging to 0 classes.
Found 0 images belonging to 0 classes.
Epoch 1/30


In [11]:
classifier.save('cnn_82_5.h5')

In [20]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

In [8]:
classifier = load_model('cnn_82_5.h5')

In [15]:
y_pred = classifier.predict_generator(test_set)
y_pred_class = np.argmax(y_pred,axis = 1) 

In [17]:
le = LabelEncoder()
j = []
for i in test_set.filenames: 
    j.append(i.split("\\")[0])
le.fit(j)
valid_actual = le.transform(j)classifier = load_model('cnn_82_5.h5')

In [21]:
confusion_mtx = confusion_matrix(valid_actual, y_pred_class) 
print(confusion_mtx)
target_names = ['class 0', 'class 1', 'class 2', 'class3','class4']
print(classification_report(valid_actual, y_pred_class, target_names=target_names))

[[154 102 138 210 191]
 [117  82 101 156 122]
 [108  70 101 172 123]
 [209 120 146 248 208]
 [152 115 162 254 192]]
             precision    recall  f1-score   support

    class 0       0.21      0.19      0.20       795
    class 1       0.17      0.14      0.15       578
    class 2       0.16      0.18      0.17       574
     class3       0.24      0.27      0.25       931
     class4       0.23      0.22      0.22       875

avg / total       0.21      0.21      0.21      3753

